// Jenkinsfile for ParksMap
podTemplate(
  label: "skopeo-pod",
  cloud: "openshift",
  inheritFrom: "maven",
  containers: [
    containerTemplate(
      name: "jnlp",
      image: "docker-registry.default.svc:5000/w054-jenkins/jenkins-slave-appdev",
      resourceRequestMemory: "2Gi",
      resourceLimitMemory: "2Gi"
    )
  ]
) {
  node('skopeo-pod') {
    echo "GUID: ${GUID}"
    echo "CLUSTER: ${CLUSTER}"
    
      //sh "cd ParksMap"
      //sh "mvn -s ../nexus_settings.xml clean package -DskipTests=true"

    // Your Pipeline Code goes here. Make sure to use the ${GUID} and ${CLUSTER} parameters where appropriate
    // You need to build the application in directory `ParksMap`.
    // Also copy "../nexus_settings.xml" to your build directory
    // and replace 'GUID' in the file with your ${GUID} to point to >your< Nexus instance
    echo "ParksMap"
    sh 'pwd; ls'
    
    stage('Checkout Source Code') {
      echo "Checking out source code..."
      git 'https://github.com/olivierlogi/advdev_homework_template.git'
    }

    def mvnCmd = "mvn -s ./nexus_settings.xml"

    def groupId = getGroupIdFromPom("./ParksMap/pom.xml")
    def artifactId = getArtifactIdFromPom("./ParksMap/pom.xml")
    def version = getVersionFromPom("./ParksMap/pom.xml")

    def devTag = "${version}-${BUILD_NUMBER}"
    def prodTag = "${version}"

    stage('Build Java jar') {
      echo "Building version ${devTag}"
      sh "${mvnCmd} -f ./ParksMap/pom.xml clean package spring-boot:repackage -DskipTests -Dcom.redhat.xpaas.repo.redhatga"
    }

    stage('Unit Tests') {
      echo "ParksMap Unit Tests"
      sh "${mvnCmd} -f ./ParksMap/pom.xml test"
    }

    stage('Code Analysis') {
      echo "Start Code analysis"
      sh "${mvnCmd} -f ./ParksMap/pom.xml sonar:sonar -Dsonar.host.url=http://sonarqube-${GUID}-sonarqube.apps.${CLUSTER} -Dsonar.projectName=${JOB_BASE_NAME}-${devTag}"
    } 

    stage('Publish to repository') {
      echo "Publishing to nexus"
      sh "${mvnCmd} -f ./ParksMap/pom.xml deploy -DskipTests=true -DaltDeploymentRepository=nexus::default::http://nexus3-${GUID}-nexus.apps.${CLUSTER}/repository/releases"
    }

    stage('Build Container Image') {
      echo "Building container image tasks:${devTag}..."
      sh "oc start-build parksmap --follow --from-file=./ParksMap/target/parksmap.jar -n ${GUID}-parks-dev"
      openshiftTag alias: 'false', destStream: 'parksmap', destTag: devTag, destinationNamespace: "${GUID}-parks-dev", namespace: "${GUID}-parks-dev", srcStream: 'parksmap', srcTag: 'latest', verbose: 'false'
    }

  }
}

// Convenience Functions to read variables from the pom.xml
// Do not change anything below this line.
def getVersionFromPom(pom) {
  def matcher = readFile(pom) =~ '<version>(.+)</version>'
  matcher ? matcher[0][1] : null
}
def getGroupIdFromPom(pom) {
  def matcher = readFile(pom) =~ '<groupId>(.+)</groupId>'
  matcher ? matcher[0][1] : null
}
def getArtifactIdFromPom(pom) {
  def matcher = readFile(pom) =~ '<artifactId>(.+)</artifactId>'
  matcher ? matcher[0][1] : null
}
