kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "mlbparks-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/franredhat/appdev-mitzicom"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: MLBParks/Jenkinsfile
