kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "nationalparks-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/olivierlogi/advdev_homework_template.git"
  strategy:
    jenkinsPipelineStrategy:
    env:
         - name: GUID
           value: ${GUID}
         - name: CLUSTER
           value: ${CLUSTER}
         - name: REPO
           value: ${REPO}
      jenkinsfilePath: Nationalparks/Jenkinsfile
