kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "parksmap-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/olivierlogi/advdev_homework_template"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: ParksMap/Jenkinsfile
